### PR TITLE
Universal enharmonic transposition.

### PR DESCRIPTION
**Pull request by josiah-wolf-oberholtzer**
- [x] support arbitrarily sharped and flatted accidentals
- [ ] NamedPitchClass should aggregate Accidental
- [ ] NamedPitch should aggregate NamedPitchClass and Octave
- [ ] support quartertone enharmonic transposition
- [ ] "unwrap" pitches smartly when formatting for LilyPond

### CODE REVIEW

**Comment by trevorbaca** [comment]
In reference to the 5-item list in the OP, the second goal ("NamedPitchClass should aggregate Accidental") appears to (kinda) already be the case.

Here's the implementation of the NamedPitchClass.accidental property:
```
def accidental(self):
        from abjad.tools import pitchtools
        return pitchtools.Accidental(self._alteration_in_semitones)
```
Hmm ... so NamedPitchClass isn't *storing* an `Accidental` instance. But NamedPitchClass is able to produce an `Accidental` instance.

Probably to satisfy this goal, NamedPitchClass should *store* an `Accidental` instance after instantiation, yes?

**Comment by trevorbaca** [comment]
We should also add in the stuff in #777 as additional goals for this feature (generalized enharmonic transposition). Because the transposition math will rely on the types of (generalized) intervals sketched in #777.

**Comment by trevorbaca** [comment]
Hey @josiah-wolf-oberholtzer, can you sketch some detail behind goal 3 in the OP ("NamedPitch should aggregate NamedPitchClass and Octave"). It'll be pretty straightforward to do, but lemme know what parts of your thinking are motivating the aggregation, primarily because we've avoided having pitch and pitch-class classes aggregate each other (at least up until this point). I'm totally down to rewire, just lemme know what stuff you see the aggregation simplifying so that we make sure we grab all the improvements when we do it.

Also, a reflection ... I suppose NamedPitch is (currently) conceptually equal to a triple of (diatonic pitch-class, accidental, octave). If we aggregate then NamedPitch will be conceptually equal to a pair of (named pitch-class, octave). Which is great. Just wanna point it out before we rewire.

**Comment by josiah-wolf-oberholtzer** [comment]
@trevorbaca The idea behind aggregation is to simplify the pitch ecosystem, and to potentially also reduce the amount of work (conceptual and computational) being done during pitch operations. 

There's currently a lot of "convert number to object back to number", "convert object to number back to object" sorts of operations going on, all of which make reading through pitchtools a little daunting.

We have classes for modeling accidentals and octaves. We even use them during the course of instantiating named pitches and pitch classes? Why not just aggregate them instead of going through boxing and unboxing the objects.

- NamedPitch
    - NamedPitchClass
        - diatonic_note_number
        - Accidental
    - Octave
- NumberedPitch
    - NumberedPitchClass
    - Octave

I'm not worried about memory footprint. And _should_ that become a concern, we can convert these pitchtools classes to use a flyweight pattern, e.g. there is only ever one C# named pitch-class in memory.

**Comment by josiah-wolf-oberholtzer** [comment]
Moot. See #954 instead.

**Pull request closed without merging**
