### PR TITLE
Add venvs and text editor clutter to gitignore

### PR DESCRIPTION
**Pull request by ajyoon**
One less thing for git newbies to be confused by when setting up.

### CODE REVIEW

**Comment by josiah-wolf-oberholtzer** [comment]
Looks good.

I gotta ask, what was the process that led to a `venv/` or `ENV/` directory being installed inside the `abjad/` directory?

**Comment by josiah-wolf-oberholtzer** [comment]
Also, why not also/instead `Envs/` or `.virtualenvs`, which are actually mentioned/created in the `virtualenvwrapper` docs/install process?

**Comment by ajyoon** [comment]
I like to keep the my venv's in project root directories for easy location. Maybe this is bad practice, but it can't hurt to cover them anyway. I've added those other names.

**Comment by josiah-wolf-oberholtzer** [comment]
Hunh. I didn't realize `virtualenv` was so un-opinionated. OK.

`virtualenvwrapper` definitely asks you to centralize, preferably within a subdirectory of `$HOME`.

**Comment by josiah-wolf-oberholtzer** [comment]
Whatever. Seems sound. Will merge after checks pass.

**Comment by ajyoon** [comment]
I'm probably doing it wrong, but maybe this will save some other soul who also does it wrong :)

**Comment by josiah-wolf-oberholtzer** [comment]
Well, I'm 100% sold now. Our `.gitignore` is based off of a much older version of that one.

Thank you! Merging.

**Pull request merged**
