### PR TITLE
Removed duplicate attachments when fusing leaves

### LINKED ISSUE #1245: Potential bug in _fuse_leaves_by_immediate_parent
When there is a grace note (or potentially other "attachments", e.g. time signature, metronome mark, as well?) attached to the first note of a logical tie that Abjad is trying to fuse, the grace note might appear in the last note, which it probably should not.

Here is an example:

```
import abjad

voice = abjad.Voice(r"\grace { b'16 } c'16 ~ c'16 ~ c'16 ~ c'16 ~ c'16 r16 r16 r16 r4 r4")
logical_tie = abjad.get.logical_tie(voice[0])
result = abjad.mutate._fuse_leaves_by_immediate_parent(logical_tie)

print(abjad.lilypond(voice))
```

which produce:
```
\new Voice
{
    \grace {
        b'16
    }
    c'4
    ~
    \grace {
        b'16
    }
    c'16
    r16
    r16
    r16
    r4
    r4
}
```

If this is indeed a bug, I might try to go ahead and fix it.

### PR DESCRIPTION
**Pull request by nivlekp**
This is an attempt to fix #1245.
At the moment, I am just removing BeforeGraceContainer and MetronomeMark, but I suspect there might be other unnecessary duplicate attachments when fusing leaves.

### CODE REVIEW

**Review by trevorbaca — CHANGES_REQUESTED** [review]
Hey @nivlekp this is great, and the changes do fix the problem of duplicate before grace, metronome mark and time signature after fusing.

However, exactly as you are suspecting, the bug does run deeper than just these three objects. Which is actually exciting, because I think we can implement a truly general solution. And the general solution will mean that we can avoid importing 20 or 30 different classes to detach after fusing.

This text box is small! ;) So I'll write more about this here below in the PR. Then maybe you can spend a day or two working on the general solution, and we'll see if we can get it?

**Comment by trevorbaca** [comment]
Hi again @nivlekp ok, you're definitely right that there are other cases. I'll give another example, and then I'll suggest a general approach you can try to potentially capture all cases.

Notice that clefs are also duplicated after notes are fused, just like you found for metronome marks and grace containers:
```
voice = abjad.Voice(r"c'16 ~ c'16 ~ c'16 ~ c'16 ~ c'16 r16 r16 r16 r4 r4")
clef = abjad.Clef("alto")
abjad.attach(clef, voice[0])
logical_tie = abjad.get.logical_tie(voice[0])
result = abjad.mutate._fuse_leaves_by_immediate_parent(logical_tie)

print(abjad.lilypond(voice))
\new Voice
{
    \clef "alto"
    c'4
    ~
    \clef "alto"
    c'16
    r16
    r16
    r16
    r4
    r4
}
```

Notice also that I've subtly changed the example to call `abjad.attach()` explicitly, instead of creating the clef with a LilyPond `\clef` command passed to Abjad's parser. This is just to draw attention to the fact that what we're debugging here are what Abjad refers to as "indicators" that are "attached."

Happily, we can retrieve (and iterate) all the objects attached to a note, rest, chord. So I think this will mean that we won't need to say `detach(TimeSignature, leaf)`, `detach(MetronomeMark, leaf)`, etc etc. I think we can just detach everything.

(Quick note, though: grace containers are almost certainly going to have to be special-cased. I'm still only imperfectly modeling grace containers in Abjad. It's ok, it just means that code exactly like this will probably have to special-case the handling of grace music. We'll return to that at the end.)

Test example with 4 indicators attached to one note. It's clear that all 4 indicators are incorrectly duplicated, and participate in this bug. I've changed voice to staff so that time signatures will not be commented out in LilyPond output:
```
staff = abjad.Staff(r"c'16 ~ c'16 ~ c'16 ~ c'16 ~ c'16 r16 r16 r16 r4 r4")
indicators = (
    abjad.Clef("alto"),
    abjad.TimeSignature((3, 4)),
    abjad.Articulation("staccato"),
    abjad.Articulation("accent"),
)
for indicator in indicators:
    abjad.attach(indicator, staff[0])
logical_tie = abjad.get.logical_tie(staff[0])
result = abjad.mutate._fuse_leaves_by_immediate_parent(logical_tie)

print(abjad.lilypond(staff))
\new Staff
{
    \time 3/4
    \clef "alto"
    c'4
    - \staccato
    - \accent
    ~
    \time 3/4
    \clef "alto"
    c'16
    - \staccato
    - \accent
    r16
    r16
    r16
    r4
    r4
}
```

Ok, now we can use `abjad.get.indicators()` to get all the indicators attached to a note, rest, chord:
```
staff = abjad.Staff(r"c'16 ~ c'16 ~ c'16 ~ c'16 ~ c'16 r16 r16 r16 r4 r4")
indicators = (
    abjad.Clef("alto"),
    abjad.TimeSignature((3, 4)),
    abjad.Articulation("staccato"),
    abjad.Articulation("accent"),
)
for indicator in indicators:
    abjad.attach(indicator, staff[0])

for indicator in abjad.get.indicators(staff[0]):
    print(repr(indicator))
    Tie()
    Clef('alto')
    TimeSignature((3, 4))
    Articulation('staccato')
    Articulation('accent')
```

Notice that `abjad.get.indicators()` also returns the tie attached to the first note.

Now we're able to detach all indicators attached to a note, rest, chord:
```
staff = abjad.Staff(r"c'16 ~ c'16 ~ c'16 ~ c'16 ~ c'16 r16 r16 r16 r4 r4")
indicators = (
    abjad.Clef("alto"),
    abjad.TimeSignature((3, 4)),
    abjad.Articulation("staccato"),
    abjad.Articulation("accent"),
)
for indicator in indicators:
    abjad.attach(indicator, staff[0])

for indicator in abjad.get.indicators(staff[0]):
    abjad.detach(indicator, staff[0])

print(abjad.lilypond(staff))
\new Staff
{
    c'16
    c'16
    ~
    c'16
    ~
    c'16
    ~
    c'16
    r16
    r16
    r16
    r4
    r4
}
```

It works.

The tie is also detached. But that's fine, because in the actual bug fix we're detach AFTER fusing (as opposed to BEFORE fusing like in these toy examples).

Only the grace container needs to special-case, as mentioned above. Just for completeness, here's an example that illustrates why:
```
staff = abjad.Staff(r"c'16 ~ c'16 ~ c'16 ~ c'16 ~ c'16 r16 r16 r16 r4 r4")
indicators = (
    abjad.BeforeGraceContainer("b'16"),
    abjad.Clef("alto"),
    abjad.TimeSignature((3, 4)),
    abjad.Articulation("staccato"),
    abjad.Articulation("accent"),
)
for indicator in indicators:
    abjad.attach(indicator, staff[0])

print(abjad.lilypond(staff))
\new Staff
{
    \grace {
        b'16
    }
    \time 3/4
    \clef "alto"
    c'16
    - \staccato
    - \accent
    ~
    c'16
    ~
    c'16
    ~
    c'16
    ~
    c'16
    r16
    r16
    r16
    r4
    r4
}

# grace containers not retrieved here:
for indicator in abjad.get.indicators(staff[0]):
    print(repr(indicator))
    Tie()
    Clef('alto')
    TimeSignature((3, 4))
    Articulation('staccato')
    Articulation('accent')

for indicator in abjad.get.indicators(staff[0]):
    abjad.detach(indicator, staff[0])

# grace container still attached:
print(abjad.lilypond(staff))
\new Staff
{
    \grace {
        b'16
    }
    c'16
    c'16
    ~
    c'16
    ~
    c'16
    ~
    c'16
    r16
    r16
    r16
    r4
    r4
}
```

So could you go back to the site of the fix in the current PR and 1. iterate the indicators-to-be-detached, and 2. preserve the special-casing of grace containers as you have it now? Oh, and maybe extend the tests (great job on the tests, btw) to include a more elaborate example with multiple indicators (something like here)?

**Comment by nivlekp** [comment]
Hi @trevorbaca, thank you very much for the feedback and the detailed suggestion. It should just be a couple of changes. Hopefully I can get this done either today or tomorrow.

**Comment by trevorbaca** [comment]
Great @nivlekp! And of course no hurry: thank you for finding an interesting bug!

**Comment by nivlekp** [comment]
Hi @trevorbaca, I noticed that there might be three kinds of indicators in this case.

The first one is what has been demonstrated before, where the indicator should only be attached to the first leaf of the logical tie after fusing.

The second kind should be attached to every leaf of the logical tie after fusing, for example, if a StemTremolo is attached to the first leaf, then it seems logical that it should be attached to every leaf. This is to ensure the behavior is consistent with the case where the new duration of the logical tie is assignable, then there will only be one leaf, and that StemTremolo is attached to this only leaf. (My logic might be wrong though)

The third kind should be attached to only the last leaf of the logical tie after fusing, for example, if a StopBeam is attached to the first leaf, then it seems logical that the StopBeam should be moved to the last leaf after fusing, with similar reasoning to the second case.

My latest commit however is not classifying properly all the indicators though, since I'm not exactly sure which case some of the indicators belong to.

However, if my logic is totally wrong, I'm happy to revert back to detaching all the indicators in the following leaves after the first leaf.

**Comment by trevorbaca** [comment]
Hi @nivlekp, once again this very good work!

Ok, this is a great discussion, and a very interesting problem to think about. You're now touching on a problem that I've been (secretly) modeling already in the codebase. In this comment I'll explain my thinking; then I'll make a recommendation for how to proceed with this PR.

First, we can call this idea you've stumbled upon something like the "time orientation" of indicators: most indicators make sense only at the start of a "note"; but a small number of indicators (bend after, breath mark, laissez vibrer) only make sense at the end of a "note." We could say that most indicators are "left-oriented" (ie, at the start of the duration the note represents) and that only more unusual indicators are "right-oriented" (ie, at the end of the duration the note represents).

As it happens, I encountered this exact problem two years ago while working on edge cases in the split code. (The split and fuse code are very tightly related.) My solution at the time was to add a private attribute -- at the level of the class -- to just those indicators that needed to be special-cased as right-oriented. Grep Abjad for "_time_orientation" and here's what you'll see:
```
$ ack _time_orientation | sort
indicators/BendAfter.py:51:    _time_orientation = enums.Right
indicators/BreathMark.py:87:    _time_orientation = enums.Right
indicators/LaissezVibrer.py:34:    _time_orientation = enums.Right
indicators/StaffChange.py:55:    _time_orientation = enums.Right
indicators/StartHairpin.py:62:    _time_orientation = enums.Right
indicators/StopBeam.py:29:    _time_orientation = enums.Right
indicators/StopGroup.py:25:    _time_orientation = enums.Right
indicators/StopPianoPedal.py:24:    _time_orientation = enums.Right
indicators/StopSlur.py:29:    _time_orientation = enums.Right
indicators/StopTrillSpan.py:29:    _time_orientation = enums.Right
mutate.py:365:        direction = getattr(indicator, "_time_orientation", enums.Left)
```
Magic! This is almost exactly the list of indicators that your PR taxonomizes with `_indicator_is_at_end()`, and even captures a few more.

(You'll notice that the only place in the code that consumes this private `_time_orientation` attribute is in `mutate.py` deep in the split code.)

It means that you can replace `_indicator_is_at_end()` entirely with `not getattr(indicator, "_time_orientation", enums.Left)`. Which is cool. (And notice that you don't have to worry about taxonomizing the indicators yourself: it's up to the author of each indicator class [me] to mark each class as either left- or right-oriented. Then the fuse / split code will handle the indicator accordingly.)

Ok so I just want to document one thing before giving the recommendation for how to move forward:

The fuse and split code are quite complex. Years of use has shown that "the right" time for users to either fuse or split notation is **before adding a bunch of indicators**. I haven't documented this anywhere at all for our users. Not yet, anyway. But it does seem to be a very important best practice for working with Abjad. Working with Abjad kind of trains composers into working "rhythm-first": build the rhythms first; then add pitches; last attach everything else (indicators). Once experienced users notice this pattern and begin to adopt it, we notice something interesting. Which is that all fuse / split / meter-rewriting / quantizing operations should happen as early in the composing process as possible. And this tends to avoid precisely the problems with thinking through the fuse / split behavior of indicators. (Because few indicators will be attached at rhythm-construction time.)

I mention this because I think that it's still possible that the long-term solution for this behavior-of-indicators-during-fuse-or-split problem that we're solving may be to just tell Abjad users "do all your fuse / split stuff before you attach a bunch of indicators."

However, for now let's solve this problem in the more general way that does, in fact, seek to accommodate the time orientation of indicators.

So here's what I'd like you to try for the next revision to this PR:

1. Extend my two-way left-oriented / right-oriented taxonomy of indicators with a third category: middle-oriented. This will let us accommodate the case of `abjad.StemTremolo` and `abjad.KeyCluster`, as you've discovered. The way you do this is very easy: go to the `StemTremolo.py` and `KeyCluster.py` modules. Then add the line `_time_orientation = enums.Middle` to each of those classes. Notice that there's a ### CLASS ATTRIBUTES ### banner in the definition of each class in Abjad. This shows you the right place to add class attributes, like `_time_orientation`.

2. Then replace `_indicator_is_at_end()` with `not getattr(indicator, "_time_orientation", enums.Right) and not getattr(indicator, "_time_orientation", enums.Middle)`.

3. Then replace `_indicator_is_continuous()` with `getattr(indicator, "_time_orientation", enums.Middle)`.

4. Then get rid of almost all those new import statements at the top of `mutate.py`! 👍 

If these ideas seem ok to you, then let's try making them and see what happens. Happily, all the new tests that you've written should continue to pass! This is a great example of using test-driven development (TDD) to solve a bug.

**Comment by nivlekp** [comment]
Thanks, @trevorbaca, for your very detailed suggestions! Now that I looked at my previous commit, it was indeed quite un-pythonic. Adding an attribute to each indicator class is definitely more elegant.

In the latest commit, I have adapted your suggestions. I noticed that there were `enums.Right`, `enums.Both`, and `enums.Left`. Since it seems that `enums.Both` was not used anywhere in the codebase, I changed it to `enums.Middle`, and used it in the `_set_leaf_duration()` function as suggested.

I agree that the least complicated way to avoid this sort of bug is to add the indicators after fusing/splitting. And In order for the Nauert extension to work properly, it seems that we only had to detach the duplicated grace, time signature, and metronome mark.

Please let me know if there's any further change that I shall make.

Again, thank you very much for your time and suggestions.

**Review by trevorbaca — APPROVED** [review]
Thanks @nivlekp! This code is great. All the tests pass. And I've also pulled and rerendered all of my own scores with the fix: everything works perfectly. Good job on this one. Thank you for the thoughtfulness of the code. I've merged into master and the fix will be included in 3.2.

**Pull request merged**
