### PR TITLE
Add type hint to from_pitch classmethod

### PR DESCRIPTION
**Pull request by jgarte**

### CODE REVIEW

**Comment by trevorbaca** [comment]
Hi @jgarte looks like mypy fails when GitHub actions runs. Did you run mypy before you opened the PR?

**Comment by jgarte** [comment]
> Hi @jgarte looks like mypy fails when GitHub actions runs. Did you run mypy before you opened the PR?

No, I didn't. 

Going to try again after I think about why mypy doesn't like that.

**Comment by trevorbaca** [comment]
The mypy developers seem to change things fairly often; make sure to update mypy on your machine (``pip install --upgrade mypy``); that might reveal a difference between the version of mypy on your laptop versus GitHub.

**Comment by jgarte** [comment]
I'll reopen this again soon once I get more time. Thanks for the tips.

**Pull request closed without merging**
