### PR TITLE
Issue 601 generalize tiespecifier

### PR DESCRIPTION
**Pull request by jdavancens**
#601

### CODE REVIEW

**Comment by josiah-wolf-oberholtzer** [comment]
@trevorbaca Take a look! 😂

**Comment by jdavancens** [comment]
Haha can I update my resume now?

**Comment by josiah-wolf-oberholtzer** [comment]
Jeez, wait until we merge it.

**Comment by josiah-wolf-oberholtzer** [comment]
@jdavancens I'm gonna let Trevor do the honor of reviewing this guy. For now, if it does what you want (and I see that all tests pass), just work on your score with this branch as your active Abjad branch.

**Comment by trevorbaca** [comment]
Hey @jdavancens this looks awesome!

The pytest tests look good. Can I make one request that you add (at least) one doctest showing the new functionality, too? A great place to do this would be in the TaleaRhythmMaker.tie_specifier docstring. There are currently five examples in the docstring. Can you add example 6 to show the new functionality? If you want to add an example 7, then feel free to do that, too. (Totally up to you: the right number of examples depends on the functionality; and you're the author so you decide.)

Also, are you able to build the API (with `avj api -M`)? If you are, make sure to do so and then take a look at the notated output created by your docstrings. It's pretty satisfying to get that type of visual feedback ;) and it'll also help you make sure that the examples you've created are musically idiomatic (or, perhaps, compositionally idiomatic). It's quite amazing how often I dream up an example for a docstring, render it as notation, read the notation, and then realize that the example just wasn't idiomatic. Building the docs and visually inspecting output is the true idiomaticity checker when we author.

Also, if you wanna be super-consistent with the most recent way we've been coding, then there a couple of small formatting things you can do in your code. I'll add those in a subsequent message.

**Comment by trevorbaca** [comment]
Hey @jdavancens, ok there's a small thing you can change in your `TieSpecifier` initializer logic (if you'd like to).

Here's what you have (I think) right now:
```
         if tie_consecutive_notes is not None:
              if isinstance(tie_consecutive_notes, bool):
                  inverted = not(tie_consecutive_notes)
                  tie_consecutive_notes = \
                      patterntools.select_all(inverted)
              elif isinstance(tie_consecutive_notes, patterntools.Pattern):
                  tie_consecutive_notes = tie_consecutive_notes
              else:
                  message = 'tie_consecutive_notes must be boolean or pattern'
                  raise Exception(message)
          self._tie_consecutive_notes = tie_consecutive_notes
```
Coercing true-valued input for `tie_consecutive_notes` to a select-all pattern makes sense.

But coercing false-valued (or none-valued) input for `tie_consecutive_notes` to a (select-none) pattern works a little less cleanly for my tastes. Why? Because there's an (unwritten!) principle we've been trying to follow that none-valued input should just remain equal to none and not be coerced to false or some other negative value (or, in this case, to a select-none type of pattern). In other words, none-valued input means "this property was never set by the composer", and it's nice to keep that clear while an object is initialized (and afterwards). This also keeps the so-called 'storage format' of objects unpolluted. (Try asking for `print(format(tie_specifier, 'storage'))` sometime. It's a really effective way of seeing all properties of an object at once, printed beautifully.)

So maybe something like this in the initializer:
```
         if tie_consecutive_notes is not None:
              if tie_consecutive_notes is True:
                  tie_consecutive_notes = patterntools.select_all()
              prototype = (bool, type(None), patterntools.Pattern, patterntools.CompoundPattern)
              if not isinstance(tie_consecutive_notes, prototype):
                  message = 'tie_consecutive_notes must be boolean, none or pattern: {!r}.'
                  message = message.format(time_consecutive_notes)
                  raise Exception(message)
          self._tie_consecutive_notes = tie_consecutive_notes
```
Note that the isinstance check currently must list `Pattern` and `CompoundPattern` individually (because neither of the two classes inherit from the other).

Note also the use of repr-printing the value of `tie_consecutive_notes` in the error message. That's a best practice we've been trying to adhere to. Because when a stray value of `tie_consecutive_notes` inevitably gets passed in when we're composing, it's super helpful to see right away what the actual input value was, because that's what's going to have to be changed next in whatever input file you're working with.

Last, note that one reason we don't have to worry about coercing false- or none-valued `tie_consecutive_notes` into a none-valued pattern is because of the first two lines of `TieSpecifier._do_tie_consecutive_notes()`:
```
    def _do_tie_consecutive_notes(self, divisions):                             
        if not self.tie_consecutive_notes:                                      
            return
        ...
```
Feel free to take any of the suggestions here!

**Comment by josiah-wolf-oberholtzer** [comment]
Ping @jdavancens. Did you get anywhere with this? I'm prepping Abjad 2.18 for release at the end of the week. If you've got stuff, let me know.

**Comment by josiah-wolf-oberholtzer** [comment]
Closing. Can be re-opened if interest remains.

**Pull request closed without merging**
